### ISSUE TITLE
[DISCUSSION] Topic matcher for subscription?

### ISSUE THREAD

**Issue by mhverbakel** [ralphtheninja/mqtt-match#20]
Hello,

We use this library in our ACL (access control list) to check if a user may subscribe or publish. I came across the following edge case, and I would like to discuss whether this is intended behaviour or not:

Filter: `test/+`
Topic: `test/#`
Result: `true`

I think this should return false (e.g. if the left is `+`, then the right should not be `#`), but this is only true for subscribe, not for publish. On the other hand, I don't think a publish to `test/#` is allowed in MQTT.

**Comment by ralphtheninja** [comment]
Why are you using `test/#` as a topic? This is confusing. It results in `true` since `test/+` would match `test/<insertwordhere>` and in this case `<insertwordhere>` corresponds to `#`.

**Comment by mhverbakel** [comment]
Our access control list looks something like this:

```
user "mhverbakel":
    allow subscribe "test/+"
```

This means that my user is allowed to subscribe to `test/banana` or `test/+`, but not to `test/banana/milkshake` or `test/#`. The latter one would then be a false positive.

**Comment by ralphtheninja** [comment]
Ok, I see what you mean. The intent of this module is to match mqtt formatted topic strings (i.e. using combinations of `+` or `#`), it's not meant to match wildcard topics against each other.

**Comment by mhverbakel** [comment]
Okay then. For anyone running into this issue, my implementation: (also checks [MQTT 4.7.2](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718108))

```ts
// Implementation inspired by mqtt-match.
// https://github.com/ralphtheninja/mqtt-match/blob/master/index.js

// If only one of the filter and topic starts with a "$", it can never match. [MQTT-v3.1.1 4.7.2]
if (filter.startsWith("$") !== topic.startsWith("$")) {
    return false;
}

// Split the levels.
const filterLevels = filter.split("/");
const topicLevels = topic.split("/");

// Iterate over the topic levels.
for (let i = 0; i < filterLevels.length; i++) {
    let filterLevel = filterLevels[i];
    const topicLevel = topicLevels[i];
    switch (filterLevel) {
        case "#":
            // The other levels don't matter, everything after this matches.
            return topicLevels.length >= filterLevels.length - 1;
        case "+":
            // Only multilevel wildcard gets rejected. [https://github.com/ralphtheninja/mqtt-match/issues/20]
            if (topicLevel === "#") {
                return false;
            }
            continue;
    }

    // Check if the filter matches the topic.
    if (filterLevel !== topicLevel) {
        return false;
    }
}

// Check that the lengths are equal.
return filterLevels.length === topicLevels.length;
```
