### ISSUE TITLE
Cannot find module 'ts-toolbelt' or its corresponding type declarations.

### ISSUE THREAD

**Issue by bmacher** [ralphtheninja/mqtt-match#27]
When using `mqtt-pattern` and trying to compile the code I get the following error: 

```sh
$ tsc --noEmit
node_modules/mqtt-pattern/index.d.ts:2:24 - error TS2307: Cannot find module 'ts-toolbelt' or its corresponding type declarations.

2 import type { F } from "ts-toolbelt";
                         ~~~~~~~~~~~~~


Found 1 error in node_modules/mqtt-pattern/index.d.ts:2

error Command failed with exit code 2.
```

Problem is that `ts-toolbelt` is neither a `dependency` nor a `peerDependency` so it will not be installed with this library. My current workaround is to install it myself as `devDependency`. However, it would be better if `mqtt-pattern` would handle this.

Spec:
mqtt-pattern: 2.0.0
node: v18.12.1
typescript: 4.9.3

**Comment by bmacher** [comment]
Wrong package. Sorry.

**Comment by ralphtheninja** [comment]
> Wrong package. Sorry.

No worries.
